### ISSUE TITLE
Alterando estrutura da api - conceitos de SOLID em JavaScript 

### ISSUE THREAD

**Issue by glaucia86** [plataforma-desafios-js/Plataforma-Desafios-JS-API#3]
Conforme falado na última live feita no Twitch, podemos adotar uma estrutura de código onde podemos realizar o **[Onion Architecture](https://dev.to/remojansen/implementing-the-onion-architecture-in-nodejs-with-typescript-and-inversifyjs-10ad)** adotando os conceitos de **[SOLID](https://en.wikipedia.org/wiki/SOLID)**. Visando deixar o código de fácil manutenção e mais limpo!

Alguns pontos que estarei reestruturado o código:

* [x] **Criando a pasta 'api' no projeto**
* [x] **Criar branch para as alterações: 'desenvolvimento-conceito-onion-architecture-api'**
* [x] **Criação do arquivo .editorconfig**
* [x] **Criar um novo arquivo .eslintrc.js**
* [x] **Alterar as configurações do arquivo 'package.json'**
* [x] **Criar arquivo: 'server.js'**
* [x] **Reestruturação das pastas**
* [x] **Renomeando os arquivos - com padrão js**
* [x] **Reestruturando o arquivo controller.js - padrão async & await**
* [x] **Reestruturando as rotas - route.js**
* [x] *Configurar o husky no 'package.json**

**(em desenvolvimento)**

**Comment by glaucia86** [comment]
@mbernardes19 e @mbernardes19 deem uma olhada no PR q mandei para vocês

PR: #4

**Comment by glaucia86** [comment]
@b3coded vc fez a live mostrando as alterações?! E testando a api?

**Comment by b3coded** [comment]
@glaucia86 PR aceita!

Vou dar uma olhada melhor e terminar o primeiro protótipo dos models
